name: Deploy Laravel Export to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite, bcmath, soap, intl, readline, ldap, msgpack, igbinary, redis, swoole, memcached, pcov, xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy .env
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          echo "APP_URL=https://trongluat11.github.io/Portflotio" >> .env
          echo "ASSET_URL=https://trongluat11.github.io/Portflotio" >> .env

      - name: Generate key
        run: php artisan key:generate

      - name: Create data directory if missing
        run: mkdir -p storage/app/data

      - name: Export Static Site
        run: php artisan export

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
